### ISSUE TITLE
Set up continuous integration to test each commit

### ISSUE THREAD

**Issue by mattbruv** [bfbbdecomp/bfbb#33]
It would be very beneficial to set up a script that downloads dependencies and tests `make` on each commit/pull request so we know that nothing is broken.

Maybe also run clang format on the C++ source too.

**Comment by DarkRTA** [comment]
>Maybe also run clang format on the C++ source too.

nah we should leave that up to the person making the pr

**Comment by mattbruv** [comment]
> > Maybe also run clang format on the C++ source too.
> 
> nah we should leave that up to the person making the pr

We should have a test to see if the code meets the linting rules though. I don't know much about CI, but maybe make it a warning if not a failure?

**Comment by DarkRTA** [comment]
>We should have a test to see if the code meets the linting rules though. I don't know much about CI, but maybe make it a warning if not a failure?

I thought you meant automatically formatting the code upon commit.
Checking it is fine but it *probably* isn't needed.

**Comment by mattbruv** [comment]
I think setting up CI should be something we do relatively soon. I also think that it should fail if the format check fails too, just to know that everything anyone opens is valid in both 🆗 and code format. I've only reviewed a single PR but I can already imagine it being annoying to have to nitpick over code formatting and double checking if the build works from scratch with each PR.
