### ISSUE TITLE
Stop stdout spam after first error

### ISSUE THREAD

**Issue by mattbruv** [bfbbdecomp/bfbb#34]
It's annoying when there are thousands of lines of errors spammed to stdout when there's some kind of CPP or linker error:
 
```
obj\src\Game\zFX.cp:6814: declaration syntax error
obj\src\Game\zFX.cp:6815: declaration syntax error
obj\src\Game\zFX.cp:6816: declaration syntax error
obj\src\Game\zFX.cp:6817: declaration syntax error
obj\src\Game\zFX.cp:6818: declaration syntax error
obj\src\Game\zFX.cp:6819: declaration syntax error
obj\src\Game\zFX.cp:6820: declaration syntax error
obj\src\Game\zFX.cp:6821: declaration syntax error
obj\src\Game\zFX.cp:6827: '}' expected
obj\src\Game\zFX.cp:6828: declaration syntax error
obj\src\Game\zFX.cp:6829: declaration syntax error
```

I'm sure there's got to be some flag or other way to stop execution after the first error encountered.

**Comment by DarkRTA** [comment]
I have plans to introduce using gcc to check syntax before attempting to compile which should hopefully resolve most of this.

mwcc's error messages are complete garbage

**Comment by seilc** [comment]
There's a compiler flag `-msgstyle` which we currently have set to `gcc`. Changing this will affect how errors are printed out. The list of arguments for `-msgstyle` are in the mwcc readme, I'll look for it tonight if needed.

**Comment by DarkRTA** [comment]
>There's a compiler flag   `-msgstyle` which we currently have set to `gcc`.

Modern versions of gcc spit out much more useful error messages than what is given by mwcc. We should definitely consider using gcc with the `-fsyntax-only` flag for syntax checking at some point.

**Comment by seilc** [comment]
Found the flag. Passing `-maxerrors 1` to the compiler and linker will make them stop printing after the 1st error:

```
obj\src\Core\x\xCollide.cpp:2392: declaration syntax error
Too many errors printed, aborting program

User break, cancelled...
make: *** [Makefile:138: obj/src/Core/x/xCollide.o] Error 2
```
