### ISSUE TITLE
Learn why floating point functions fail

### ISSUE THREAD

**Issue by mattbruv** [bfbbdecomp/bfbb#59]
We have so many big functions that are nearly perfect, except for the fact that the floating point registers are swapped. Figuring out why this happens is important. Is it a compiler setting? Do we have the wrong compiler?

It may be worth writing a program which tries to run `make` with different permutations of compiler settings with a failing floating point function that we are certain should match.

**Comment by mattbruv** [comment]
`Seil 12/26/2020`
i think i know what the issue is with floats causing functions to be nonmatching
basically, all float constants are stored in the .sdata2 section. everything in that section is considered to be const data
so if you use the same float constant multiple times, the compiler will try to optimize it to where it only reads the float constant once instead of multiple times
for example, if you use a float constant inside a for loop, the compiler will actually move the lfs instruction outside of the loop, because the float constant in memory is not expected to change, so it only needs to be loaded once
however, more often than not, it seems like in the original asm, .sdata2 is NOT treated as const data. there are instances where the same float constant is loaded multiple times in the original asm but will only be loaded once in our asm. or a float constant will be loaded inside a loop in the original asm but loaded outside the loop in our asm
interestingly, this has only happened to me when using float literals. if i leave the float in the asm and extern it out, it's more likely that the compiler will load the float multiple times. maybe extern symbols in .sdata2 are not treated as const by default?
unfortunately I have yet to figure out how to force that behavior when using float literals. I've tried adding (DATA) to the .sdata2 section in the .lcf file, I've tried using every compiler from 1.1 to 2.7, I've tried messing with compiler flags, and I haven't been able to get that behavior to happen

**Comment by mattbruv** [comment]
https://github.com/bfbbdecomp/bfbb/pull/118

**Comment by mattbruv** [comment]
This shouldn't be as big of a problem for us anymore. We have a shiftable build now and can work around floating point issues, the code doesn't have to match 100% as long as it matches functionally.

**Comment by SquareMan** [comment]
Changing this to not planned rather than completed, since we're simply working around it now, but would still like to fix the issue in the possible f possible.
